# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artile',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0\u7ba1\u7406', 'verbose_name_plural': '\u6587\u7ae0\u7ba1\u7406'},
        ),
    ]
